timestamp=2023-02-10 14:43:02.818321 level=INFO pyFile=myTools.py pyLine=174 pyFunc=LogMe msg="New work item added in queue"   svc=migrate   meteor=BER590   work_item={'meteor': 'BER590', 'info': 'BER590', 'spanID': 'Start BER590 migration'} 

[10/Feb/2023 14:43:02] "POST /app/svc HTTP/1.1" 200 49

timestamp=2023-02-10 14:44:38.532288 level=INFO pyFile=myTools.py pyLine=174 pyFunc=LogMe msg="first archive inserted, id: 115764, from date: 2021-01-28 14:40:00" traceID=3039 spanID=8aa52   svc=migrate   meteor=BER590 

108.39s - Error when waiting for filesystem changes in FSNotifyThread.
Traceback (most recent call last):
  File "/Users/nico/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 325, in _on_run
    for change_enum, change_path in self.watcher.iter_changes():
  File "/Users/nico/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydev_bundle/fsnotify/__init__.py", line 301, in iter_changes
    path_watcher._check(single_visit_info, append_change, old_file_to_mtime)
  File "/Users/nico/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydev_bundle/fsnotify/__init__.py", line 166, in _check
    self._check_dir(self._root_path, single_visit_info, append_change, old_file_to_mtime, 0)
  File "/Users/nico/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydev_bundle/fsnotify/__init__.py", line 148, in _check_dir
    self._check_dir(entry.path, single_visit_info, append_change, old_file_to_mtime, level + 1)
  File "/Users/nico/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydev_bundle/fsnotify/__init__.py", line 148, in _check_dir
    self._check_dir(entry.path, single_visit_info, append_change, old_file_to_mtime, level + 1)
  File "/Users/nico/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydev_bundle/fsnotify/__init__.py", line 148, in _check_dir
    self._check_dir(entry.path, single_visit_info, append_change, old_file_to_mtime, level + 1)
  [Previous line repeated 2 more times]
  File "/Users/nico/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydev_bundle/fsnotify/__init__.py", line 143, in _check_dir
    time.sleep(self.sleep_time)
OverflowError: timestamp too large to convert to C _PyTime_t

timestamp=2023-02-10 14:44:48.267810 level=INFO pyFile=myTools.py pyLine=174 pyFunc=LogMe msg="obs inserted, last id: 123491, date: 2021-02-11 07:00:00" traceID=3039 spanID=8aa52   svc=migrate   meteor=BER590 

unsupported operand type(s) for %: 'datetime.datetime' and 'int'

timestamp=2023-02-10 14:44:48.307618 level=CRITICAL pyFile=myTools.py pyLine=174 pyFunc=LogMe msg="<class 'TypeError'>:unsupported operand type(s) for %: 'datetime.datetime' and 'int'" traceID=3039 spanID=8aa52   stack=  File "/Users/nico/projects/climato_test/app/classes/migrate/migrate.py", line 819, in roundDatetimeToAnExactDay
    return timestamp - (timestamp % 86400)

  File "/Users/nico/projects/climato_test/app/classes/migrate/migrate.py", line 383, in loadExistingRecordsAndFlush
    self.load_maxmin_from_weewx(work_item['meteor'], new_records, self.roundDatetimeToAnExactDay(start_dt), self.roundDatetimeToAnExactDay(end_dt), my_span)

  File "/Users/nico/projects/climato_test/app/classes/migrate/migrate.py", line 398, in loadExistingRecordsAndFlush
    raise ex
 
timestamp=2023-02-10 14:44:48.311813 level=CRITICAL pyFile=myTools.py pyLine=174 pyFunc=LogMe msg="<class 'TypeError'>:unsupported operand type(s) for %: 'datetime.datetime' and 'int'" traceID=3039 spanID=8aa52   svc=svcMigrate   work_item={'meteor': 'BER590', 'info': 'BER590', 'spanID': 'Start BER590 migration', 'pid': 4}   stack=  File "/Users/nico/projects/climato_test/app/classes/migrate/migrate.py", line 819, in roundDatetimeToAnExactDay
    return timestamp - (timestamp % 86400)

  File "/Users/nico/projects/climato_test/app/classes/migrate/migrate.py", line 383, in loadExistingRecordsAndFlush
    self.load_maxmin_from_weewx(work_item['meteor'], new_records, self.roundDatetimeToAnExactDay(start_dt), self.roundDatetimeToAnExactDay(end_dt), my_span)

  File "/Users/nico/projects/climato_test/app/classes/migrate/migrate.py", line 398, in loadExistingRecordsAndFlush
    raise ex
 
Span: Start BER590 migration
  attributes:
             job: django, info: BER590, meteor: BER590, 
  events:
         obs: 3864 rows inserted (with deca == 0), total rows: 7728
         histo: 7728 rows inserted
         maxmin_step1: mesures ajout√©es en cache: 177744
         insert_obs_minmax_from_weewx: processing: 767.059 ms
         exception: unsupported operand type(s) for %: 'datetime.datetime' and 'int'
         exception: unsupported operand type(s) for %: 'datetime.datetime' and 'int'
timestamp=2023-02-10 14:44:48.315195 level=INFO pyFile=myTools.py pyLine=174 pyFunc=LogMe msg="Stop command received"   svc=svcMigrate   status=stopped 

